add git information docs reference and example
cypress-io/github-action pull request #1091
Opened 2023-12-06 17:11 UTC by conversayShawn

2023-12-06 17:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/github-action?pullRequest=1091) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/github-action?pullRequest=1091) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/github-action?pullRequest=1091) it.</sub>

2023-12-06 19:36 UTC, MikeMcC399 commented
It seems that this PR is related to a Discord post https://discord.com/channels/755913899261296641/1181347411940102294 about merge queues.

Please describe in the added documentation in what situations additional environment variables are needed to be set up as when I look at the results of running [.github/workflows/example-recording.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-recording.yml) sometimes the branch is correctly recorded in Cypress Cloud and sometimes not.

Does [.github/workflows/example-recording.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-recording.yml) need to be updated?

2023-12-06 22:33 UTC, conversayShawn commented
@MikeMcC399 

> If "Cloud" means "Cypress Cloud" then please change the terms to say "Cypress Cloud" explicitly.
Good call.

> Does it relate to https://github.com/cypress-io/github-action#automatic-pr-number--url-detection and should it be placed adjacent to this section?
It appears some of the info might be more readable with different structuring. Let me know if this grouping is a viable option.

> It seems that this PR is related to a Discord post https://discord.com/channels/755913899261296641/1181347411940102294 about merge queues.
Correct. The main goal here is to make it as simple as possible for users to find their answers in the documentation. 

> Does [.github/workflows/example-recording.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-recording.yml) need to be updated?
Possibly, but it's not a necessity.

2023-12-07 09:34 UTC, MikeMcC399 requested changes
Git is written uppercase (see https://git-scm.com/)

2023-12-07 09:37 UTC, MikeMcC399 commented on README.md
> +Please refer to the [Cypress Cloud git information environment variables](https://docs.cypress.io/guides/continuous-integration/introduction#Git-information) section in our documentation for more exa
```suggestion
Please refer to the [Cypress Cloud Git information environment variables](https://on.cypress.io/guides/continuous-integration/introduction#Git-information) section in our documentation for more examples.
```

2023-12-07 15:40 UTC, MikeMcC399 commented on README.md
> +To record the project needs `projectId` and `recordKey`. Typically this value is saved in the [Cypress Configuration File](https://docs.cypress.io/guides/references/configuration#Configuration-File).
This needs to be reworded to be correct. My suggestion to remove `recordKey` was not correct, so I deleted it.

2023-12-07 15:57 UTC, conversayShawn commented on README.md
> +To record the project needs `projectId` and `recordKey`. Typically this value is saved in the [Cypress Configuration File](https://docs.cypress.io/guides/references/configuration#Configuration-File).
I can see your point here, so I reworded it to provide clarity.

2023-12-08 23:32 UTC, jennifer-shehane approved these changes

2023-12-08 23:33 UTC, merged