fix: make headed execution available again
cypress-io/github-action pull request #409
Opened 2021-08-03 16:47 UTC by sergiubcn

- Addresses issue [#403](https://github.com/cypress-io/github-action/issues/403);
- Because `cypress run` executes tests in `headless` mode by default we need to bring back the flag which toggles `headed` vs `headless` execution in CI;

2021-08-03 16:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/github-action?pullRequest=409) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/github-action?pullRequest=409) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/github-action?pullRequest=409) it.</sub>

2021-08-04 07:39 UTC, steveworkman commented
By taking away the `headless` option, anyone using Cypress < 8 won't be able to turn headless on any more. This is either a breaking change or should support both options

2021-08-04 16:33 UTC, sergiubcn commented
> By taking away the `headless` option, anyone using Cypress < 8 won't be able to turn headless on any more. This is either a breaking change or should support both options

Definitely a good point. I just wasn't sure what the desired approach is. I'll push a new change tomorrow, though folks who haven't specified this option at all, expecting the execution in `headed` mode as per < v7.x will still have to updated their pipeline configs.
Thanks for checking this!

2021-08-05 07:32 UTC, sergiubcn commented on dist/index.js
> +    cmd.push('--headed')
This change makes it backwards compatible, but v8+ users cannot benefit from the `headless` by default mode.

2021-08-05 07:43 UTC, sergiubcn commented
@bahmutov when you have a few minutes can you please provide some insights into the desired approach? Do we want to push a new version with a breaking change or make it backwards compatible?

2021-09-15 14:41 UTC, jennifer-shehane requested changes
The default for all `cypress run` runs should be headless for all 8+ users, without them having to pass any option to GitHub Actions. There was a clear intent behind this change from the product and this should be the default behavior. There should be an option to allow people to change the run to run as 'headed' if specified.

2021-09-17 12:54 UTC, Sergiu-B commented
@jennifer-shehane That was my initial assumption as well - if a project updates to Cypress v8+ it should update the GHAction as well. Addressed. TY!

2021-09-17 12:57 UTC, sergiubcn commented
@jennifer-shehane That was my initial assumption as well - if a project is updated to Cypress v8+ it should have the GH Action updated as well. Addressed. TY!

2021-10-21 23:45 UTC, gajus commented
Is there any workaround for this at the moment?

2021-11-17 08:52 UTC, villanuevaSEAT approved these changes

2021-11-17 08:53 UTC, villanuevaSEAT commented
We need this! 🙏

2021-11-17 08:58 UTC, gagle commented
@jennifer-shehane

2021-11-17 08:58 UTC, villanuevaSEAT commented
@jennifer-shehane can you approve this and remove the "request changes"? Thanks!

2022-01-24 15:26 UTC, pmegremis commented
@jennifer-shehane any update on this?
Thanks!

2022-04-19 13:22 UTC, didaktio commented
@jennifer-shehane et al. You are there, , and everywhere. Hear is undefined. Can you here?

2022-06-02 02:59 UTC, GusPrice commented
Would love to see this get merged in. Our pipelines are failing recently b/c they are randomly running some headless and some not? Tried setting `headless: false` but clearly that does nothing.

2022-06-03 04:04 UTC, admah commented
@sergiubcn I'm sorry that this has taken so long to get merged in. Is there any way for you to resolved the conflicts listed here or to give me write access in your fork so I can resolve them myself? If neither of those options work, I can also create another PR and reference back to this one. Thank you!

2022-06-06 16:30 UTC, sergiubcn commented
@admah Added you as a collaborator. I had a few days off, but I hope to get to this tomorrow, unless you beat me to it. :)

2022-06-07 13:19 UTC, sergiubcn commented
✅ Done! Ready for review.

2022-06-08 12:12 UTC, robertguss approved these changes

2022-06-08 15:24 UTC, admah approved these changes

2022-06-08 15:25 UTC, merged